🎨 add err function to jazz

diff --git a/bin/jazz b/bin/jazz
--- a/bin/jazz
+++ b/bin/jazz
@@ -26,6 +26,10 @@ function help() {
   echo "+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+="
 }
 
+function err() {
+  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@" >&2
+}
+
 function update_e2e() {
   echo ""
   echo " 🚀 pushing the $1 branch to e2e.edvisor.io "
@@ -48,7 +52,7 @@ function run_suite() {
   echo " ✅ TESTING with the $1 suite"
   echo "                    --- 🤖"
   echo ""
-  cd /Users/Beastie/development/edvisorio/web-client-e2e && LM=true ./node_modules/protractor/bin/protractor protractor.conf.js --suite $1
+  cd /Users/Beastie/development/edvisorio/web-client-e2e && CI=true CIRCLE_BRANCH='master' LM=true ./node_modules/protractor/bin/protractor protractor.conf.js --suite $1
   woohoo
 }
 
@@ -92,7 +96,8 @@ function woohoo () {
 
 function woops () {
   echo ""
-  echo " 🚫 woops, can't do that 🚫 "
+  err " 🚫 woops, can't do that 🚫 "
+  exit "${1}"
   echo ""
 }
 
